const fs = require('fs');
const path = require('path');
const vm = require('vm');

const source = fs.readFileSync(
  path.join(__dirname, '../../js/modules/education/edu-course-session.js'),
  'utf8'
);

function loadCourseSessionApp(overrides = {}) {
  const app = {
    _courseSessionCache: {},
    _getEduTeamRecord: jest.fn(() => overrides.team || {
      leader: '課務負責人',
      coaches: ['王教練'],
      contact: 'line@example',
    }),
    generateWeeklyDates: jest.fn((plan) => overrides.weeklyDates || []),
  };
  const context = {
    App: app,
    console,
    Date,
    String,
    Number,
    Math,
    Array,
    Object,
    Set,
    Map,
    parseInt,
  };
  vm.runInNewContext(source, context, { filename: 'edu-course-session.js' });
  return context.App;
}

describe('edu course session auto sync helpers', () => {
  test('session plan creates only missing numbered sessions', () => {
    const app = loadCourseSessionApp();
    const missing = app._buildMissingAutoCourseSessions('teamA', {
      id: 'planA',
      planType: 'session',
      name: '堂數班',
      totalSessions: 3,
      startDate: '2099-06-01',
      endDate: '2099-06-15',
      maxCapacity: 8,
      location: '球場 A',
    }, [{
      id: 'manual',
      title: '手動第一堂',
      date: '2099-06-01',
      startTime: '19:00',
    }], ['stu1', 'stu2']);

    expect(missing).toHaveLength(2);
    expect(missing.map(item => item.id)).toEqual(['auto_session_2', 'auto_session_3']);
    expect(missing.map(item => item.sessionNumber)).toEqual([2, 3]);
    expect(missing.map(item => item.date)).toEqual(['2099-06-08', '2099-06-15']);
    expect(missing[0]).toMatchObject({
      title: '第 2 堂課',
      location: '球場 A',
      capacity: 8,
      studentIds: ['stu1', 'stu2'],
      autoGenerated: true,
      autoSource: 'session-plan',
    });
  });

  test('session plan auto sessions use explicit session schedules', () => {
    const app = loadCourseSessionApp();
    const missing = app._buildMissingAutoCourseSessions('teamA', {
      id: 'planA',
      planType: 'session',
      name: '堂數班',
      totalSessions: 2,
      startDate: '2099-06-01',
      endDate: '2099-06-15',
      sessionSchedules: [
        { date: '2099-06-03', startTime: '18:00', endTime: '19:00' },
        { date: '2099-06-10', startTime: '20:00', endTime: '21:30' },
      ],
    }, [], ['stu1']);

    expect(missing).toHaveLength(2);
    expect(missing.map(item => ({
      date: item.date,
      startTime: item.startTime,
      endTime: item.endTime,
    }))).toEqual([
      { date: '2099-06-03', startTime: '18:00', endTime: '19:00' },
      { date: '2099-06-10', startTime: '20:00', endTime: '21:30' },
    ]);
  });

  test('weekly plan creates missing sessions from generated course dates', () => {
    const app = loadCourseSessionApp({
      weeklyDates: ['2099-06-01', '2099-06-08'],
    });
    const missing = app._buildMissingAutoCourseSessions('teamA', {
      id: 'weeklyA',
      planType: 'weekly',
      weekdays: [1],
      timeSlot: '09:00-10:30',
      startDate: '2099-06-01',
      endDate: '2099-06-15',
      maxCapacity: 6,
      location: '球場 B',
    }, [{
      id: 'existing',
      date: '2099-06-01',
      startTime: '09:00',
    }], ['stu1']);

    expect(missing).toHaveLength(1);
    expect(missing[0]).toMatchObject({
      id: 'auto_weekly_20990608',
      title: '第 2 堂課',
      date: '2099-06-08',
      startTime: '09:00',
      endTime: '10:30',
      studentIds: ['stu1'],
      autoGenerated: true,
      autoSource: 'weekly-plan',
    });
  });
});
