const fs = require('fs');
const path = require('path');
const vm = require('vm');

const source = fs.readFileSync(
  path.join(__dirname, '../../js/modules/education/edu-course-session.js'),
  'utf8'
);

function loadCourseSessionApp(overrides = {}) {
  const app = {
    _courseSessionCache: {},
    _getEduTeamRecord: jest.fn(() => overrides.team || {
      leader: '課務負責人',
      coaches: ['王教練'],
      contact: 'line@example',
    }),
    generateWeeklyDates: jest.fn((plan) => overrides.weeklyDates || []),
  };
  const context = {
    App: app,
    FirebaseService: overrides.FirebaseService || {},
    escapeHTML,
    console,
    Date,
    String,
    Number,
    Math,
    Array,
    Object,
    Set,
    Map,
    parseInt,
  };
  vm.runInNewContext(source, context, { filename: 'edu-course-session.js' });
  return context.App;
}

function escapeHTML(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

describe('edu course session auto sync helpers', () => {
  test('course session student tags hide age for non staff viewers', () => {
    const app = loadCourseSessionApp();
    app.calcAge = jest.fn(() => 11);
    const student = { id: 'stuA', gender: 'female', birthday: '2015-01-01', groupNames: ['Group A'] };

    const viewerHtml = app._renderCourseSessionStudentTags(student, {}, {}, { isStaff: false });
    const staffHtml = app._renderCourseSessionStudentTags(student, {}, {}, { isStaff: true });

    expect(viewerHtml).not.toContain('edu-session-student-slot-age');
    expect(viewerHtml).not.toContain('11歲');
    expect(staffHtml).toContain('edu-session-student-slot-age');
    expect(staffHtml).toContain('11歲');
    expect(app.calcAge).toHaveBeenCalledTimes(1);
  });

  test('session plan creates only missing numbered sessions', () => {
    const app = loadCourseSessionApp();
    const missing = app._buildMissingAutoCourseSessions('teamA', {
      id: 'planA',
      planType: 'session',
      name: '堂數班',
      totalSessions: 3,
      startDate: '2099-06-01',
      endDate: '2099-06-15',
      maxCapacity: 8,
      location: '球場 A',
    }, [{
      id: 'manual',
      title: '手動第一堂',
      date: '2099-06-01',
      startTime: '19:00',
    }], ['stu1', 'stu2']);

    expect(missing).toHaveLength(2);
    expect(missing.map(item => item.id)).toEqual(['auto_session_2', 'auto_session_3']);
    expect(missing.map(item => item.sessionNumber)).toEqual([2, 3]);
    expect(missing.map(item => item.date)).toEqual(['2099-06-08', '2099-06-15']);
    expect(missing[0]).toMatchObject({
      title: '第 2 堂課',
      location: '球場 A',
      capacity: 8,
      studentIds: ['stu1', 'stu2'],
      autoGenerated: true,
      autoSource: 'session-plan',
    });
  });

  test('session plan auto sessions use explicit session schedules', () => {
    const app = loadCourseSessionApp();
    const missing = app._buildMissingAutoCourseSessions('teamA', {
      id: 'planA',
      planType: 'session',
      name: '堂數班',
      totalSessions: 2,
      startDate: '2099-06-01',
      endDate: '2099-06-15',
      sessionSchedules: [
        { date: '2099-06-03', startTime: '18:00', endTime: '19:00' },
        { date: '2099-06-10', startTime: '20:00', endTime: '21:30' },
      ],
    }, [], ['stu1']);

    expect(missing).toHaveLength(2);
    expect(missing.map(item => ({
      date: item.date,
      startTime: item.startTime,
      endTime: item.endTime,
    }))).toEqual([
      { date: '2099-06-03', startTime: '18:00', endTime: '19:00' },
      { date: '2099-06-10', startTime: '20:00', endTime: '21:30' },
    ]);
  });

  test('weekly plan creates missing sessions from generated course dates', () => {
    const app = loadCourseSessionApp({
      weeklyDates: ['2099-06-01', '2099-06-08'],
    });
    const missing = app._buildMissingAutoCourseSessions('teamA', {
      id: 'weeklyA',
      planType: 'weekly',
      weekdays: [1],
      timeSlot: '09:00-10:30',
      startDate: '2099-06-01',
      endDate: '2099-06-15',
      maxCapacity: 6,
      location: '球場 B',
    }, [{
      id: 'existing',
      date: '2099-06-01',
      startTime: '09:00',
    }], ['stu1']);

    expect(missing).toHaveLength(1);
    expect(missing[0]).toMatchObject({
      id: 'auto_weekly_20990608',
      title: '第 2 堂課',
      date: '2099-06-08',
      startTime: '09:00',
      endTime: '10:30',
      studentIds: ['stu1'],
      autoGenerated: true,
      autoSource: 'weekly-plan',
    });
  });

  test('auto sync updates existing future sessions and freezes completed sessions', async () => {
    const existing = [
      {
        id: 'auto_session_1',
        sessionNumber: 1,
        autoGenerated: true,
        autoSource: 'session-plan',
        status: 'scheduled',
        date: '2099-06-01',
        startTime: '19:00',
        endTime: '20:30',
        location: 'Old Field',
        capacity: 6,
        studentIds: ['stu1'],
      },
      {
        id: 'auto_session_2',
        sessionNumber: 2,
        autoGenerated: true,
        autoSource: 'session-plan',
        status: 'done',
        date: '2099-06-08',
        startTime: '19:00',
        endTime: '20:30',
        location: 'Frozen Field',
        capacity: 6,
        studentIds: ['stu1'],
      },
    ];
    const updateCourseSession = jest.fn(async () => ({ ok: true }));
    const app = loadCourseSessionApp({
      FirebaseService: {
        createCourseSession: jest.fn(),
        updateCourseSession,
      },
    });
    app._loadCourseSessions = jest.fn(async () => existing);
    app._getCoursePlanAutoSessionStudentIds = jest.fn(async () => ['stu1', 'stu2', 'stu3']);

    const result = await app._ensureCoursePlanSessionsFromPlan('teamA', {
      id: 'planA',
      planType: 'session',
      totalSessions: 2,
      maxCapacity: 10,
      location: 'New Field',
      sessionSchedules: [
        { date: '2099-06-03', startTime: '18:00', endTime: '19:00' },
        { date: '2099-06-10', startTime: '20:00', endTime: '21:00' },
      ],
    });

    expect(result).toMatchObject({ created: 0, updated: 1 });
    expect(updateCourseSession).toHaveBeenCalledWith('teamA', 'planA', 'auto_session_1', expect.objectContaining({
      date: '2099-06-03',
      startTime: '18:00',
      endTime: '19:00',
      location: 'New Field',
      capacity: 10,
      studentIds: ['stu1', 'stu2', 'stu3'],
    }));
    expect(updateCourseSession).not.toHaveBeenCalledWith('teamA', 'planA', 'auto_session_2', expect.anything());
    expect(existing[0]).toMatchObject({
      date: '2099-06-03',
      startTime: '18:00',
      endTime: '19:00',
      studentIds: ['stu1', 'stu2', 'stu3'],
    });
    expect(existing[1]).toMatchObject({
      date: '2099-06-08',
      startTime: '19:00',
      studentIds: ['stu1'],
    });
  });

  test('auto sync freezes started and cancelled sessions', async () => {
    const nowSpy = jest.spyOn(Date, 'now').mockReturnValue(new Date('2099-06-08T20:00:00').getTime());
    try {
      const existing = [
        {
          id: 'auto_session_1',
          sessionNumber: 1,
          autoGenerated: true,
          autoSource: 'session-plan',
          status: 'scheduled',
          date: '2099-06-08',
          startTime: '19:00',
          endTime: '20:30',
          location: 'Started Field',
          capacity: 6,
          studentIds: ['stu1'],
        },
        {
          id: 'auto_session_2',
          sessionNumber: 2,
          autoGenerated: true,
          autoSource: 'session-plan',
          status: 'cancelled',
          date: '2099-06-15',
          startTime: '19:00',
          endTime: '20:30',
          location: 'Cancelled Field',
          capacity: 6,
          studentIds: ['stu1'],
        },
      ];
      const updateCourseSession = jest.fn(async () => ({ ok: true }));
      const app = loadCourseSessionApp({
        FirebaseService: {
          createCourseSession: jest.fn(),
          updateCourseSession,
        },
      });
      app._loadCourseSessions = jest.fn(async () => existing);
      app._getCoursePlanAutoSessionStudentIds = jest.fn(async () => ['stu1', 'stu2']);

      const result = await app._ensureCoursePlanSessionsFromPlan('teamA', {
        id: 'planA',
        planType: 'session',
        totalSessions: 2,
        maxCapacity: 10,
        location: 'New Field',
        sessionSchedules: [
          { date: '2099-06-10', startTime: '18:00', endTime: '19:00' },
          { date: '2099-06-17', startTime: '20:00', endTime: '21:00' },
        ],
      });

      expect(result).toMatchObject({ created: 0, updated: 0 });
      expect(updateCourseSession).not.toHaveBeenCalled();
      expect(existing[0]).toMatchObject({ date: '2099-06-08', studentIds: ['stu1'] });
      expect(existing[1]).toMatchObject({ date: '2099-06-15', studentIds: ['stu1'] });
    } finally {
      nowSpy.mockRestore();
    }
  });
  test('weekly auto sync updates existing sessions when course dates and time change', async () => {
    const existing = [
      {
        id: 'auto_weekly_20990601',
        sessionNumber: 1,
        autoGenerated: true,
        autoSource: 'weekly-plan',
        status: 'scheduled',
        date: '2099-06-01',
        startTime: '09:00',
        endTime: '10:30',
        location: 'Old Field',
        capacity: 6,
        studentIds: ['stu1'],
      },
      {
        id: 'auto_weekly_20990608',
        sessionNumber: 2,
        autoGenerated: true,
        autoSource: 'weekly-plan',
        status: 'scheduled',
        date: '2099-06-08',
        startTime: '09:00',
        endTime: '10:30',
        location: 'Old Field',
        capacity: 6,
        studentIds: ['stu1'],
      },
    ];
    const updateCourseSession = jest.fn(async () => ({ ok: true }));
    const app = loadCourseSessionApp({
      weeklyDates: ['2099-06-03', '2099-06-10'],
      FirebaseService: {
        createCourseSession: jest.fn(),
        updateCourseSession,
      },
    });
    app._loadCourseSessions = jest.fn(async () => existing);
    app._getCoursePlanAutoSessionStudentIds = jest.fn(async () => ['stu1', 'stu2']);

    const result = await app._ensureCoursePlanSessionsFromPlan('teamA', {
      id: 'weeklyA',
      planType: 'weekly',
      timeSlot: '18:00-19:30',
      maxCapacity: 12,
      location: 'New Field',
    });

    expect(result).toMatchObject({ created: 0, updated: 2 });
    expect(updateCourseSession).toHaveBeenCalledWith('teamA', 'weeklyA', 'auto_weekly_20990601', expect.objectContaining({
      date: '2099-06-03',
      startTime: '18:00',
      endTime: '19:30',
      location: 'New Field',
      capacity: 12,
      studentIds: ['stu1', 'stu2'],
    }));
    expect(updateCourseSession).toHaveBeenCalledWith('teamA', 'weeklyA', 'auto_weekly_20990608', expect.objectContaining({
      date: '2099-06-10',
      startTime: '18:00',
      endTime: '19:30',
      location: 'New Field',
      capacity: 12,
      studentIds: ['stu1', 'stu2'],
    }));
    expect(existing[0]).toMatchObject({
      date: '2099-06-03',
      startTime: '18:00',
      endTime: '19:30',
      location: 'New Field',
    });
  });
});
